export const COLOR_PATHS = [
  "1_bit/black_and_white",
  "1_bit/green_and_purple",
  "1_bit/pink_and_black",
  "1_bit/red_and_white",
  "blue",
  "default_green",
  "grey",
  "lime_green",
  "orange",
  "pink",
  "purple",
  "red",
  "white",
  "yellow"
];

export const COLOR_RAW = [
  "1_bit_black_and_white",
  "1_bit_green_and_purple",
  "1_bit_pink_and_black",
  "1_bit_red_and_white",
  "blue",
  "default_green",
  "grey",
  "lime_green",
  "orange",
  "pink",
  "purple",
  "red",
  "white",
  "yellow"
];

export const COLOR_ASCII_PATHS = [
  "1_bit/black_and_white",
  "1_bit/green_and_purple",
  "1_bit/black_and_white",
  "1_bit/red_and_white",
  "default",
  "default",
  "default",
  "default",
  "default",
  "default",
  "purple",
  "default",
  "default",
  "default"
];

export const COLOR_ASCII_RAW = [
  "1_bit_black_and_white",
  "1_bit_green_and_purple",
  "1_bit_black_and_white",
  "1_bit_red_and_white",
  "default",
  "default",
  "default",
  "default",
  "default",
  "default",
  "purple",
  "default",
  "default",
  "default"
];

export const FACE_MAP = {
  "._.": "ascii/1",
  ".w.": "ascii/2",
  "n_n": "ascii/3",
  ">_>": "ascii/4",
  "^-^": "ascii/5",
  "v_v": "ascii/6",
  "o_O": "ascii/7",
  "O_o": "ascii/8",
  "-_-": "ascii/9",
  "x_x ": "ascii/10",
  "o_o": "ascii/11",
  "O_0": "ascii/12",
  "Teddy": "ascii/14",
  "Disapproval": "ascii/15",
  "HeartS": "ascii/16",
  "Impacted": "ascii/17",
  "Sideeye": "ascii/18",
  "Lenny 2": "ascii/19",
  ":3": "ascii/20",
  "Unamused": "ascii/21",
  "Ou0": "ascii/22",
  "Concerned": "ascii/23",
  "Lenny 1": "ascii/24",
  "Serious Teddy": "ascii/25",
  "Drip": "drip",
  "Insectoid": "face_insect_1",
  "Insectoid (Partisan)": "face_insect_2",
  "N+B": "face_nuts_and_bolts",
  "Sensor": "face_sensor",
  "Sated": "face_tongue",
  "Hungry": "face_tongue_v2",
  "Wassie": "head_wassie",
  "Jiangshi Hat": "head_jiangshi",
  "Sunglasses": "head_sunglasses",
  "Nerd": "head_nerd",
  "Third Eye": "head_third_eye",
};

export const FACE_RAW_MAP = {
  "._.": "ascii_1",
  ".w.": "ascii_2",
  "n_n": "ascii_3",
  ">_>": "ascii_4",
  "^-^": "ascii_5",
  "v_v": "ascii_6",
  "o_O": "ascii_7",
  "O_o": "ascii_8",
  "-_-": "ascii_9",
  "x_x ": "ascii_10",
  "o_o": "ascii_11",
  "O_0": "ascii_12",
  "Teddy": "ascii_14",
  "Disapproval": "ascii_15",
  "HeartS": "ascii_16",
  "Impacted": "ascii_17",
  "Sideeye": "ascii_18",
  "Lenny 2": "ascii_19",
  ":3": "ascii_20",
  "Unamused": "ascii_21",
  "Ou0": "ascii_22",
  "Concerned": "ascii_23",
  "Lenny 1": "ascii_24",
  "Serious Teddy": "ascii_25",
  "Drip": "drip",
  "Insectoid": "face_insect_1",
  "Insectoid (Partisan)": "face_insect_2",
  "N+B": "face_nuts_and_bolts",
  "Sensor": "face_sensor",
  "Sated": "face_tongue",
  "Hungry": "face_tongue_v2",
  "Wassie": "wassie",
  "Jiangshi Hat": "jiangshi",
  "Sunglasses": "sunglasses",
  "Nerd": "nerd",
  "Third Eye": "third_eye",
};

export const BODY_MAP = {
  "Battery": "battery",
  "Bee": "bee",
  "Butterfly": "butterfly",
  "Caterpillar": "caterpillar",
  "Cube": "cube",
  "Ghost": "default",
  "Drip": "drip",
  "Lightbulb": "lightbulb",
  "Working CRT Monitor ": "monitor",
  "Broken CRT Monitor": "monitor_broken",
  "Octahedron": "octahedron",
  "Octopus": "octopus",
  "Orb": "orb",
  "Pumpkin": "pumpkin",
  "Tube": "tube",
  "Jellyfish": "jellyfish",
  "Eyes": "eerie_eyes",
  "Amphora": "amphora",
  "Shrimp": "shrimp",
  "Spider": "spider",
  "Plant": "plant",
  "Magatama": "magatama",
  "Snake": "snake",
  "Tank": "tank",
  "Hagoromo": "hagoromo",
  "Lotus": "lotus",
  "Ant": "ant",
  "Soda Cup": "soda",
  "Suit": "suit",
  "No Kami": "no_kamis",
};

export const HANDS_MAP = {
  "Candles": "candles",
  "Spectral": "claws",
  "Spinning Coins": "coins_v2",
  "Coins": "coins_static",
  "Orbs": "default",
  "Eyeballs": "eyeballs",
  "Fan Blades": "fan_front", 
  "Fan Blades (Back)": "fan_back",
  "Beetle": "insect_basic",
  "Insectoid": "insect_basic",
  "Mantis": "mantis",
  "Paws": "paws",
  "Plugs": "plugs",
  "Scorpion": "scorpion",
  "Tentacles": "tentacles",
  "Toasters": "toasters",
  "UFO Catcher": "ufo_catcher",
  "Wrenches": "wrenches",
  "Mole Cricket": "mole_cricket",
  "Plant": "plant",
  "Guns": "gun",
  "Torus": "torus",
  "Crab": "crab",
  "Melted": "melted",
  "Wassie Flipper": "wassie",
  "Mudra": "mudra",
  "Van de Graaf": "van_de_graaf_generator",
  "Fairy": "fairy_wings",
  "Wings": "wings",
};

export const BG_MAP = {
  "Blue": "blue",
  "Blue-Grey": "blue_grey",
  "Default Green": "default_green",
  "Alt Green": "green",
  "Grey!": "grey",
  "Hot Pink": "hot_pink",
  "Lavender!": "lavender",
  "BOG": "matrix_2/black_on_green",
  "BSOD ": "matrix_2/bsod",
  "GOB": "matrix_2/green_on_black",
  "PURPLE!!!": "matrix_2/purple_on_black",
  "RED!!!": "matrix_2/red_on_black",
  "GREY!!!!": "matrix_2/white_on_black",
  "Mustard": "mustard",
  "Orange": "orange",
  "Pink": "pink",
  "Purple": "purple",
  "Red!": "red",
  "Rust": "rust",
  "White!": "white",
  "Yellow": "yellow",
  "Butterfly": "butterfly",
  "Maze": "maze",
  "Nature 1": "nature_1",
  "Nature 2": "nature_2",
  "Nature 3": "nature_3",
  "Textbook": "textbook",
  "Graveyard": "graveyard",
};

export const BG_RAW_MAP = {
  "Blue": "blue",
  "Blue-Grey": "blue_grey",
  "Default Green": "default_green",
  "Alt Green": "green",
  "Grey!": "grey",
  "Hot Pink": "hot_pink",
  "Lavender!": "lavender",
  "BOG": "matrix_2_black_on_green",
  "BSOD ": "matrix_2_bsod",
  "GOB": "matrix_2_green_on_black",
  "PURPLE!!!": "matrix_2_purple_on_black",
  "RED!!!": "matrix_2_red_on_black",
  "GREY!!!!": "matrix_2_white_on_black",
  "Mustard": "mustard",
  "Orange": "orange",
  "Pink": "pink",
  "Purple": "purple",
  "Red!": "red",
  "Rust": "rust",
  "White!": "white",
  "Yellow": "yellow",
  "Butterfly": "butterfly",
  "Maze": "maze",
  "Nature 1": "nature_1",
  "Nature 2": "nature_2",
  "Nature 3": "nature_3",
  "Textbook": "textbook",
  "Graveyard": "graveyard",
};

export const COLOR_MAP = {
  "1BIT BW": 0,
  "1BIT GREEN": 1,
  "1BIT PINK": 2,
  "1BIT WR": 3,
  "Blue": 4,
  "Green": 5,
  "Grey": 6,
  "Lime Green": 7,
  "Orange": 8,
  "Pink": 9,
  "Purple": 10,
  "Red": 11,
  "White": 12,
  "Yellow": 13,
};

export const SHADOW_FOLDER_MAP = [
  "matrix_white_on_black",
  "matrix_green_on_black",
  "matrix_purple_on_black",
  "matrix_red",
  "blue",
  "default_green",
  "grey",
  "green",
  "orange",
  "pink",
  "purple",
  "red",
  "white",
  "yellow",
];

export const SHADOW_FILE_MAP = [
  "matrix_white_on_black",
  "matrix_green_on_black",
  "matrix_purple_on_black",
  "matrix_red",
  "shadow_blue",
  "shadow_default_green",
  "shadow_grey",
  "shadow_green",
  "shadow_orange",
  "shadow_pink",
  "shadow_purple",
  "shadow_red",
  "shadow_white",
  "shadow_yellow",
];

